const postStatus = [
    "fullfilled",
    "offer", 
    "is_escrowed",
    "escrowed by admin",
    "escrowed by admin team",
    "escrowed by third party",
    "held by escrow",
    "completed",
    "canceled",
    "not escrowed. Go at your own risk.",
    "signed",
    "ongoing",
    "shitpost",
]